spring.application.name=com.api


server.port=8081
jwt.secret=MiClaveSecretaSuperSeguraYEscondida123456789!#%&_ParaMiProyectoTodoAppAngularYSpringBoot

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=mappings

# CONFIGURACIÓN CLIENTE OAUTH2 - MICROSOFT ENTRA ID
spring.security.oauth2.client.registration.azure.client-id=23ef36d5-26ad-4c39-b382-27047fdacdf4

spring.security.oauth2.client.registration.azure.scope=openid,profile,email
spring.security.oauth2.client.registration.azure.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.azure.client-name=Microsoft Entra ID

# CONFIGURACIÓN DEL PROVEEDOR
# Reemplaza {tenant} por tu Tenant ID específico o por 'common' si es multitenant
spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/3dab7f41-fc0a-47ab-8502-8c5f5c726674/v2.0

#spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/{tenant}/v2.0
