spring.application.name=com.api


server.port=8081
google.client-id=762559686416-2had8klsm955lmnboc8eioa52ul6ke5e.apps.googleusercontent.com
jwt.secret=MiClaveSecretaSuperSeguraYEscondida123456789!#%&_ParaMiProyectoTodoAppAngularYSpringBoot

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=mappings
